### ISSUE TITLE
Moving windows impossible or very laggy

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra-html5#188]
Hi,

I'm on the latest commit of xpra-html5 and xpra (as of now) and it's impossible to move windows of apps for some of them, and very laggy for others.

I'm not sure what info I can provide to help you debug this? I need to stay on the bleeding edge until the keycloak commits make it to a release (maybe that's already the case?).

Edit:
xpra latest commit
xpra-html5 commit ecc3a08 (keycloack commit)

fixes the bug.

If I manage to find the incriminating xpra-html5 commit I'll let you know. Do you know what could be the issue?

**Comment by totaam** [comment]
The keycloak commit is part of the 5.0 release which is the current version.

Moving windows with the html5 client is done purely client side so it should never be slower than what your browser can achieve - easily 60fps or higher.
That's assuming that your session is seamless.

**Comment by iDmple** [comment]
Does the version 5 already have a .deb?

I'm working on finding which commit causes the issue. I'll provide the commit hash.

**Comment by iDmple** [comment]
The issue comes from this commit: ced316f4833d80f80d238aa7252628f18d2faed8

What other info can I provide?

**Comment by totaam** [comment]
@iDmple that's post 5.0 release, and since it is fixed in current master - can we close this?
Things occasionally break in the beta channel, that's what it is for.

**Comment by iDmple** [comment]
It's not fixed, it breaks from this commit! All commits from this one are affected by the bug.

I can try the current .deb to see if the bug has made it to the release.

**Comment by totaam** [comment]
> It's not fixed ...

You said:
> xpra-html5 commit https://github.com/Xpra-org/xpra-html5/commit/ecc3a0819807d5174d28b6bc76e498d9af3b92fa (keycloack commit) fixes the bug.

Is that not true then?

> Does the version 5 already have a .deb?

Every distro should have a version 5.0 build of `xpra-html5` in the stable repository, yes.

**Comment by iDmple** [comment]
What fixes the bug is going back to a previous commit. All commits before ced316f4833d80f80d238aa7252628f18d2faed8 aren't affected, for example ecc3a0819807d5174d28b6bc76e498d9af3b92fa.

I took the time to find out that the bug was introduced in ced316f4833d80f80d238aa7252628f18d2faed8 to help you.

**Comment by iDmple** [comment]
https://user-images.githubusercontent.com/5065505/170078599-3b83d974-4346-4aaa-b994-ed5386046863.mov

Here you can see the issue. The server log has the same message. No errors. In the latest commit I can move some applications but not hyper, and they lag. But it looks like in this commit I can't move any app at all. In the previous commit before the bug is introduced, everything is good.

**Comment by iDmple** [comment]
It looks like keycloak isn't working in the release. I will try to find out what's wrong and if I can't I'll open another ticket.

**Comment by totaam** [comment]
TIL: clearly this is not a regular window move, the window is not managed by the browser, it uses the X11 "initiate move resize" method.

The latest code handling this action:
https://github.com/Xpra-org/xpra-html5/blob/16d9dd570f597469e4315fbc852db0245c0ecffb/html5/js/Window.js#L1163-L1169
Looks identical to older versions:
https://github.com/Xpra-org/xpra-html5/blob/ec2d300f5a8232c72992390bb5ba5e7a53449119/html5/js/Window.js#L1062-L1068

So the problem comes from somewhere else, perhaps the part that prepares the `div` value.


> It looks like keycloak isn't working in the release.
> Edit: my bad, keycloak works fine in the release :)

#164 just like https://github.com/Xpra-org/xpra/pull/3486 lacks unit tests or even validation instructions.
So it is untestable and may well break without anyone knowing.

**Comment by iDmple** [comment]
I only showed you this window, because the other windows (none of them can move) don't even show anything in the logs when I try to move them.

So maybe the problem is something completely different?

**Comment by totaam** [comment]
> I only showed you this window, ..

I can reproduce the problem with any application that use CSD windows, but not with any regular windows, like an xterm.
I assume that you haven't tried just a simple test application like a terminal.

**Comment by iDmple** [comment]
I made some additional tests:

- commit ced316f (first bad commit)
While reading the code I seemed to see some confusion between this and me, and this is now confirmed with the errors I got in this screenshot:
<img width="1556" alt="Screenshot 2022-05-30 at 12 19 54" src="https://user-images.githubusercontent.com/5065505/170978789-97f9911c-b96e-44b1-92be-d72d3e63b8f7.png">
These errors don't appear in the latest commit, see below.

Video: https://user-images.githubusercontent.com/5065505/170981168-4bf20f0b-b6d3-4d7a-8eb2-069354f41e05.mov

- latest commit as of today 7768af9
Hyper isn't moving. Xterm can move but seems to get stuck at the top portion of the screen. When I first opened the issue I had tried with another app, which got stuck around the middle of the screen, so it seemed to be lagging when passing the middle. With the newest commit of today, this app can't move at all.
Video:
https://user-images.githubusercontent.com/5065505/170980576-ec989a85-92e7-40b9-a495-9bc7a556eaf6.mov

- commit ecc3a08 (keycloack commit)
Fully functional just like any other commit before ced316f
Video:
https://user-images.githubusercontent.com/5065505/170980875-fad0f55b-9cf0-46d1-a689-656146d0187f.mov

**Comment by totaam** [comment]
And now it doesn't... At least I can reproduce the problem now. Will fix.
There are already a number of fixes recorded in #183

**Comment by iDmple** [comment]
Great I could help. I can test after you have fixed it, if you like. Thanks for always being so reactive!

**Comment by totaam** [comment]
What breaks non-CSD window moves in ced316f4833d80f80d238aa7252628f18d2faed8 is just this missing chunk:
```patch
diff --git a/html5/js/Window.js b/html5/js/Window.js
index a8ba036..8052411 100644
--- a/html5/js/Window.js
+++ b/html5/js/Window.js
@@ -154,7 +154,7 @@ XpraWindow.prototype.add_window_decorations = function() {
                }
        });
        jQuery(this.div).on("dragstart", (ev) => {
-               client.release_buttons(ev, me);
+               client.release_buttons(ev, this);
                this.set_focus_cb(this);
                client.mouse_grabbed = true;
        });
```
This was causing the `dragstart` handler to fail.

The problem is that something else broke since then because this fix is already in master, yet it still doesn't work there.
Then the lagginess is also caused by the same commit - but fortunately, this is no longer a problem in git master!

Bisecting requires re-adding:
```
	const client = this.client;
```
And points to b923bfd6dadc73dfc5141a59a5ca80933e53914b - the commit above fixes that.

New beta builds with this fix will be uploaded later today.

**Comment by iDmple** [comment]
I finally tested the latest commit 56f906c4b86ab95371586cd0cfcd571dbf43d2c4, and there are still issues with moving windows. Here is a new video:

https://user-images.githubusercontent.com/5065505/175278808-c232d720-6703-45ac-afa0-03179e39024d.mov

There is also an issue with js syntax:
https://github.com/Xpra-org/xpra-html5/blob/56f906c4b86ab95371586cd0cfcd571dbf43d2c4/html5/js/Client.js#L2154-L2157
With this syntax, `this` automatically gets bound to the function itself and in that context the `debug` method is undefined. Perhaps you meant to use an arrow function there, which doesn't rebind `this`?

I don't think this is related to the fact the windows don't move though?

**Comment by totaam** [comment]
> I don't think this is related to the fact the windows don't move though?

Probably not, this is an asynchronous function, so it shouldn't affect callers of `read_clipboard_text` via `_poll_clipboard` - but it does get called from `do_window_mouse_click`.

In any case, I'm not seeing this problem.
Please specify the **exact** application which is not moving, have you tried an `xterm`?

**Comment by iDmple** [comment]
The application in the video is https://hyper.is/, an electron app.
I'm going to try an xterm right now, as well as the fix for the clipboard.

**Comment by iDmple** [comment]
The clipboard issue is resolved.

For xterm, I have the laggy behavior I was trying to describe above:

https://user-images.githubusercontent.com/5065505/175297559-2ffed452-6606-41d2-b78c-5d3393b5025e.mov

https://user-images.githubusercontent.com/5065505/175297566-bcdf713b-245b-4878-b9b9-e63aeadbae35.mov

The video is split in two because it's too big.

I can try to help debug this if you let me know how?

**Comment by TijZwa** [comment]
I can reproduce the issue and see whats going on. If your cursor hits another window while dragging, the event is passed to client.js and evaluated with ```return window == undefined```
If this returs false (as it does) the drag will stop.

I've created PR 199 (https://github.com/Xpra-org/xpra-html5/pull/199)  for this issue.


@iDmple Can you test this change and confirm?
You can simply replace line 1706 - 1709 in client.js with:

```
    if (this.mouse_grabbed) {
      return true;
    }

    if (this.server_readonly || !this.connected) {
      return window == undefined;
    }
```
