### ISSUE TITLE
can't remove on-screen keyboard through config

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra-html5#47]
I'm using xpra-html5 on a headless server inside a docker container, and the on-screen keyboard shows up. I can't find a way to deactivate it via the config file.

Could you please let me know how to do that?

**Comment by totaam** [comment]
> I can't find a way to deactivate it via the config file

Which config file are you referring to?
The html5 client options are described here:
https://github.com/Xpra-org/xpra-html5/blob/master/docs/Configuration.md

The on-screen keyboard is configured using the `keyboard` option.
The two commits above fix mobile device detection, so the on-screen keyboard will no longer be shown by default unless you're browsing from a mobile or tablet.

**Comment by iDmple** [comment]
I'm referring to xpra.conf. Options in there have no effect on xpra-html5? I see that there is https://github.com/Xpra-org/xpra-html5/blob/master/html5/default-settings.txt, I'm going to see if I can somehow remove it from there.

The URL parameters work for now.

Do you know if those commits are included in the xpra version packaged for ubuntu-20.04?

**Comment by totaam** [comment]
> I'm referring to xpra.conf

That's only used by the server, though some of these options will apply to all clients. (but not the on-screen keyboard, which only exists in the html5 client)

> The URL parameters work for now.

OK. I'm closing this ticket then.

> Do you know if those commits are included in the xpra version packaged for ubuntu-20.04?

The 4.2 release will be out soon and will be packaged for Ubuntu 20.04 in the xpra.org repositories.

**Comment by iDmple** [comment]
Ok for xpra.conf. Changing default-settings.txt did not seem to have any effect.

I will wait for the 4.2 release, thanks for answering me and clarifying those points this fast!

**Comment by iDmple** [comment]
Hi,

I'm now using these versions on Ubuntu 20.04:
- xpra                 4.2-r0-1
- xpra-html5      4.2-r1-1 

and the on-screen keyboard still appears.

Is this normal?

Thanks for your help.

**Comment by totaam** [comment]
> Is this normal?

No. Sorry. I had missed one location.
This is now fixed and will be in the next update. You can apply the trivial change above.

**Comment by iDmple** [comment]
Perfect many thanks :)

**Comment by iDmple** [comment]
Hi again,

The keyboard is still showing in groovy (xpra repos). The versions that are installed are:

- xpra 4.1.3-r1-1
- xpra-html5 4.1.2

Would it be possible to get newer versions?

Thanks!

**Comment by totaam** [comment]
A new release of the html5 client will happen quite soon but you will not get packages for groovy anywhere:
https://lists.ubuntu.com/archives/ubuntu-announce/2021-July/000270.html

**Comment by iDmple** [comment]
Whoops, somehow I missed that!
I'll go to 21.04 then!

Thanks
